run:
  skip-files:
    - "main.go"
output:
  sort-results: true
  format: checkstyle:lint-report.out
linters:
  enable-all: true
  disable:
    - deadcode
    - depguard
    - exhaustivestruct
    - exhaustruct
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - goerr113
    - gofumpt
    - golint
    - ifshort
    - interfacer
    - ireturn
    - maligned
    - noctx
    - nosnakecase
    - paralleltest
    - scopelint
    - structcheck
    - tagliatelle
    - unconvert
    - varcheck
    - wastedassign
    - wrapcheck
